
name: New Run Python Unit Tests

on:
  push:
    branches:
      - '**'        # matches every branch
      - '!main'     # excludes main

concurrency: run-python-unit-tests

env:
  PYTHON_VERSION: "3.9"
  POETRY_VERSION: "1.4.2"
  POETRY_URL: https://install.python-poetry.org

jobs:
  run-python-unit-tests:

    runs-on: [self-hosted, pytest]

    steps:
      - name: Git checkout
        uses: actions/checkout@v3
          
      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      # Install Poetry
      - name: Install Poetry ${{ env.POETRY_VERSION }}
        run: |
          curl -sSL ${{ env.POETRY_URL }} | python - --version ${{ env.POETRY_VERSION }}
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      # Configure Code Artifact
      - name: Configure Code Artifact
        env:
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEV }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_DEV }}
          AWS_DEFAULT_REGION: eu-central-1
          AWS_ACCOUNT: ${{ secrets.AWS_ACCOUNT_DEV }}
        run: |
          export SSH_AUTH_SOCK=${{ env.SSH_AUTH_SOCK }}
          export SSH_AGENT_PID=${{ env.SSH_AGENT_PID }}

          export AWS_DEFAULT_REGION=eu-north-1

          export AWS_CODEARTIFACT_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY_DEV }}
          export AWS_CODEARTIFACT_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID_DEV }}
          export AWS_CODEARTIFACT_ACCOUNT=${{ secrets.AWS_ACCOUNT_DEV }}

          aws codeartifact login --tool pip --repository devocean-repo --domain devocean-domain --domain-owner ${{ secrets.AWS_ACCOUNT_DEV }}
          export CODEARTIFACT_AUTH_TOKEN=`aws codeartifact get-authorization-token --domain devocean-domain --domain-owner ${{ secrets.AWS_ACCOUNT_DEV }} --query authorizationToken --output text`

          $HOME/.local/bin/poetry source add --secondary devocean-repo https://devocean-domain-${{ secrets.AWS_ACCOUNT_DEV }}.d.codeartifact.eu-north-1.amazonaws.com/pypi/devocean-repo/simple/

          $HOME/.local/bin/poetry config http-basic.devocean-repo aws $CODEARTIFACT_AUTH_TOKEN

#      - name: Poetry Install
#        env:
#          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEV }}
#          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_DEV }}
#          AWS_DEFAULT_REGION: eu-central-1
#          AWS_ACCOUNT: ${{ secrets.AWS_ACCOUNT_DEV }}
#        run: |
#          $HOME/.local/bin/poetry install

#      - name: Store Poetry Deps Cache(If not hit)
#        if: steps.poetry-cache.outputs.cache-hit != 'true'
#        id: store-cache-poetry-deps
#        uses: actions/cache/save@v3
#        with:
#          path: |
#            ~/.local
#          key: poetry-local-${{ runner.os }}-${{ steps.setup_python.outputs.python-version }}-${{ hashFiles('**/poetry.lock') }}

      - name: Install Deps
        run: |
          $HOME/.local/bin/poetry add pytest
          $HOME/.local/bin/poetry add pytest-custom_exit_code
          $HOME/.local/bin/poetry install

      - name: Run tests
        env:
          AWS_DEFAULT_REGION: us-west-2
          AWS_ACCESS_KEY_ID: testing
          AWS_SECRET_ACCESS_KEY: testing
          AWS_SECURITY_TOKEN: testing
          AWS_SESSION_TOKEN: testing
        run: |
          $HOME/.local/bin/poetry run pytest --suppress-no-test-exit-code -vvv

